development:
  adapter: postgresql
  database: room_eez_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: room_eez_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: room_eez_production
  pool: 5
  timeout: 5000
